/**
 * @file tkl_sleep.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between
 * BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_sleep.h"
#include "tuya_error_code.h"

static uint8_t       s_awake_req = 0;
static TUYA_SLEEP_CB_T s_sleep_cb;
static BOOL_T        s_cb_valid  = FALSE;
// --- END: user defines and implements ---

/**
 * @brief sleep callback register
 *
 * @param[in] sleep_cb:  sleep callback
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_cpu_sleep_callback_register(TUYA_SLEEP_CB_T *sleep_cb)
{
    TKL_UNUSED(sleep_cb);
    // --- BEGIN: user implements ---
    if (NULL == sleep_cb) {
        return OPRT_INVALID_PARM;
    }
    s_sleep_cb = *sleep_cb;
    s_cb_valid = TRUE;
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief allow to sleep
 *
 * @param[in] none
 *
 * @return none
 */
void tkl_cpu_allow_sleep(void)
{
    // --- BEGIN: user implements ---
    if (s_awake_req > 0) {
        s_awake_req--;
    }
    // --- END: user implements ---
}

/**
 * @brief force wakeup
 *
 * @param[in] none
 *
 * @return none
 */
void tkl_cpu_force_wakeup(void)
{
    // --- BEGIN: user implements ---
    if (s_awake_req < 255) {
        s_awake_req++;
    }
    // --- END: user implements ---
}

/**
 * @brief Set the low power mode of CPU
 *
 * @param[in] enable: enable switch
 * @param[in] mode:   cpu sleep mode
 *
 * @note This API is used for setting the low power mode of CPU.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_cpu_sleep_mode_set(BOOL_T enable, TUYA_CPU_SLEEP_MODE_E mode)
{
    TKL_UNUSED(enable);
    TKL_UNUSED(mode);
    // --- BEGIN: user implements ---
    if (TUYA_CPU_DEEP_SLEEP == mode) {
        if (enable) {
            return OPRT_NOT_SUPPORTED;
        }
        if (s_awake_req > 0) {
            s_awake_req--;
        }
        return OPRT_OK;
    }
    if (enable) {
        if (s_awake_req > 0) {
            s_awake_req--;
        }
    } else {
        if (s_awake_req < 255) {
            s_awake_req++;
        }
    }
    return OPRT_OK;
    // --- END: user implements ---
}
